# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

GUIDESTAR_USER: "dannyyu92@gmail.com"
GUIDESTAR_PW: "saasbook"
ALCHEMY_KEY: "5c314204bc868beb7516d5a02d3f1c149d364dae"
JUSTGIVING_KEY: "f4530b29"